services:
  postgres:
    image: postgres:13   # готовый образ, никакой сборки
    container_name: delivery_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      SECRET_HASH: ${SECRET_HASH}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh   # монтируем init.sh
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-webserver:
    build: .                     # использует ваш единственный Dockerfile
    container_name: delivery_airflow_webserver
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW_CONN_POSTGRES_DEFAULT: postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./analytics:/opt/airflow/analytics
      - ./logs:/opt/airflow/logs
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    command: ["webserver"]

  airflow-scheduler:
    build: .                     # тот же Dockerfile
    container_name: delivery_airflow_scheduler
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW_CONN_POSTGRES_DEFAULT: postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./analytics:/opt/airflow/analytics
      - ./logs:/opt/airflow/logs
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    command: ["scheduler"]

volumes:
  postgres_data: